Fix integer overflows and reduce attack surface
QubesOS/qubes-rpm pull request #3
Opened 2021-03-29 20:29 UTC by DemiMarie

This fixes CVE-2021-20248 and CVE-2021-20249, as well as generally
reducing attack surface.  Specifically:

- Signature headers are required to be a single contiguous region.

- Counts are checked for validity before being used.

- Integer overflow in computing blob->ril (CVE-2021-20248) is prevented
  by negating *after* division.

- Integer wraparound in computing blob->rdl (CVE-2021-20249) is
  prevented by using GCC’s __builtin_add_overflow().

- Tag data entries in package headers are required to be sorted and
  unique.

This does change the observable behavior of RPM in some cases, beyond
mere bug fixes:

- Packages with a non-contiguous signature header will be rejected.  RPM
  never generates such packages, and while RPMv6 might, RPMv6 is
  backwards-incompatible in any case.  The change was made in upstream
  RPM to support packages generated by third-party signing tools.

- Packages that have a header lacking a region will be rejected.  RPM
  has not generated such packages since no later than 2004.

- Packages that do not have sorted tags will be rejected.  Some buggy
  versions of RPM generated them.

It also changes where some packages are rejected:

- An abort() call is added in hdrblobGet() for corrupt entries, which
  would have been rejected earlier anyway.

- Empty regions are now rejected in hdrblobVerifyRegion().  They were
  rejected in regionSwab() already.

- Excessive counts were already rejected in regionSwab(), but not before
  causing overflows in dataLength().  That isn’t exploitable, but better
  to just reject it in hdrblobVerifyInfo(), which is where the check
  really belongs.

2021-04-05 17:13 UTC, marmarek requested changes

2021-04-05 17:13 UTC, marmarek commented on rpm.spec
> -Patch910: Verify-lengths-in-hdrblobInit.patch
Please also remove the old file.

2021-04-05 17:13 UTC, marmarek commented on 0009-Reject-RPMv3-packages.patch
> ++	    rc = RPMRC_NOTFOUND;
This could _really_ use some better description, it is very not obvious how this is related to RPMv3.

2021-04-05 17:13 UTC, marmarek commented on 0010-Force-GCC-to-behave-as-RPM-expects.patch
> ++	if (len <= 0 || blob->dl - info.offset < len)
How does it ensure that `blob->dl - info.offset` cannot underflow?

2021-04-05 17:13 UTC, marmarek commented on 0010-Force-GCC-to-behave-as-RPM-expects.patch
> ++	if (length <= 0 || (se && length > se - s))
This change of semantics requires a bit more explanation. Is it really guaranteed that no header has empty data (`count == 0`)? Can you point at some tags list that hints what sizes are expected?

2021-04-05 17:13 UTC, marmarek commented on 0011-hdrblobVerifyInfo-check-region-consistency.patch
> +checked.
This patch looks like either a valid check (that should be accepted upstream), or wrong a thing to do. Can you point at relevant PR upstream (or create one)?

2021-04-05 17:13 UTC, marmarek commented on 0012-hdrblobInit-check-that-padding-is-zeroed-and-minimal.patch
> ++	    memcmp(ds + end, "\0\0\0\0\0\0\0\0", info.offset - end))
This could use some assert that 8 zeroes are enough (they are, by looking at `typeAlign`).

2021-04-05 17:13 UTC, marmarek commented on 0013-hdrblobInit-reject-trailing-junk.patch
> ++	ei2h(pe + i, &info);
I find `pe + i` harder to read than `&pe[i]`. Is there any specific reason for this change?

2021-04-05 17:13 UTC, marmarek commented on 0013-hdrblobInit-reject-trailing-junk.patch
> ++	/* We must not break sooner so that end is properly updated */
This depends on patch 11, so if patch 11 turns out to be invalid, this one too.

2021-04-05 17:52 UTC, DemiMarie commented on 0010-Force-GCC-to-behave-as-RPM-expects.patch
> ++#define	RPM_MIN_TYPE		1
This is wrong as `RPM_MIN_TYPE` is part of the public API, so this is both an API and ABI break.  I will change `hdrchkType()` instead.

2021-04-05 17:52 UTC, DemiMarie commented on 0016-Top-level-signatures-must-stand-alone.patch
> +and allowint it increases attack surface significantly.
```suggestion
and allowing it increases attack surface significantly.
```

2021-04-05 18:07 UTC, DemiMarie commented on 0009-Reject-RPMv3-packages.patch
> ++	    rc = RPMRC_NOTFOUND;
RPMv4 packages have an immutable region trailer.  RPMv3 packages do not.

2021-04-05 18:07 UTC, DemiMarie commented on 0010-Force-GCC-to-behave-as-RPM-expects.patch
> ++	if (len <= 0 || blob->dl - info.offset < len)
The above `hdrchkRange(info.offset, blob->dl)` handles that.

2021-04-05 18:07 UTC, DemiMarie commented on 0010-Force-GCC-to-behave-as-RPM-expects.patch
> ++	if (length <= 0 || (se && length > se - s))
Yes; see https://github.com/rpm-software-management/rpm/pull/1496

2021-04-05 18:07 UTC, DemiMarie commented on 0011-hdrblobVerifyInfo-check-region-consistency.patch
> +checked.
https://github.com/rpm-software-management/rpm/pull/1613

2021-04-05 18:07 UTC, DemiMarie commented on rpm.spec
> -Patch910: Verify-lengths-in-hdrblobInit.patch
Oops!

2021-04-06 03:45 UTC, marmarek commented
PipelineRetry

2021-04-06 03:51 UTC, marmarek commented
It looks good now. Please test on at least the following cases:
 - package from Fedora 25 repo
 - package from Qubes repo, built with old rpm (xfwm4 for example)
 - package from Qubes repo, built with new rpm (qubes-core-admin-linux should do)
 - template package

I think `rpmkeys -Kv` and `rpm -qip` should cover changed code enough.

2021-04-06 08:21 UTC, fepitre commented
PipelineRefresh

2021-04-06 08:21 UTC, fepitre commented
PipelineRetry

2021-04-06 16:53 UTC, DemiMarie commented
> It looks good now. Please test on at least the following cases:
> 
> * package from Fedora 25 repo
> * package from Qubes repo, built with old rpm (xfwm4 for example)
> * package from Qubes repo, built with new rpm (qubes-core-admin-linux should do)
> * template package
> 
> I think `rpmkeys -Kv` and `rpm -qip` should cover changed code enough.

All pass

2021-04-06 19:10 UTC, DemiMarie commented
Turns out that the padding checks rely critically on `end` being correct in `hdrblobVerifyInfo`, which is not always the case until the region consistency check patch is applied.  @marmarek should we ship both or neither patch?

2021-04-06 19:21 UTC, marmarek commented
In this case I'd say neither.

2021-04-08 02:20 UTC, DemiMarie commented
@marmarek thanks for adding the test!  I am no expert on GitHub Actions.

2021-04-08 02:25 UTC, marmarek commented
PipelineRefresh

2021-04-08 02:25 UTC, marmarek approved these changes

2021-04-08 03:48 UTC, merged

2021-04-08 05:39 UTC, DemiMarie commented
Thanks!